
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import random
import smtplib
from email.message import EmailMessage
import ssl
import os
from tkinter import *

# Generate a random 6-digit number
num = random.randint(100000, 999999)
os.environ['EMAIL_PASS'] = 'omsm cmtw vxem vlju'

EMAIL_ADDRESS = 'husseinemad064@gmail.com'
# email_receiver = 'husseinemad064@gmail.com'
EMAIL_PASSWORD = os.environ.get('EMAIL_PASS')

# from tkinter import *
# Explicit imports to satisfy Flake8


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\cv\interns\Sync's Interns\Python Developer\Task2\Tkinter-Designer\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



window = Tk()

verified = PhotoImage(file = r'build\assets\frame0\verified.png')
wrong = PhotoImage(file = r'build\assets\frame0\wrong.png')

def send_email():
    global num
    body=f"""
    Your OTP Verification Code is {num}
    """
    em = EmailMessage()
    em['From'] = EMAIL_ADDRESS
    em['To'] = entry_1.get()
    em['Subject'] = f'OTP Verification Code Delivered'
    em.set_content(body)

    with smtplib.SMTP_SSL('smtp.gmail.com',465) as smtp:
        smtp.login(EMAIL_ADDRESS,EMAIL_PASSWORD)
        smtp.send_message(em)

    window=Toplevel()

    Label(
        window,
        text="Code Sended Successfully",
        padx=10,
        pady=10,
        image=verified,
        compound="right",
        font=('Cairo',20)
    ).pack(expand=True,fill="both",padx=15,pady=15)

    window.mainloop()
    
    
def verify():

    if entry_2.get() == str(num):
        window=Toplevel()

        Label(
            window,
            text="Email Verified",
            padx=10,
            pady=10,
            image=verified,
            compound= "right",
            font=('Cairo',20)
        ).pack(expand=True,fill="both",padx=15,pady=15)

        entry_2.delete(0,END)
        entry_1.delete(0,END)
        
    else:
        window=Toplevel()

        Label(
            window,
            text="OTP Code MissMatched",
            padx=10,
            pady=10,
            image=wrong,
            compound= "right",
            font=('Cairo',20)
        ).pack(expand=True,fill="both",padx=15,pady=15)

        entry_2.delete(0,END)





window.geometry("412x446")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#EEEEEE",
    height = 446,
    width = 412,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    317.0,
    314.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    509.0,
    80.0,
    fill="#0E09E7",
    outline="")

canvas.create_text(
    22.0,
    18.0,
    anchor="nw",
    text="OTP Verify",
    fill="#FFFFFF",
    font=("Cairo", 24 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    357.0,
    40.0,
    image=image_image_2
)

canvas.create_text(
    16.0,
    94.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Cairo", 20 * -1)
)

canvas.create_text(
    17.0,
    223.0,
    anchor="nw",
    text="OTP",
    fill="#000000",
    font=("Cairo", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    182.5,
    164.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font=('Cairo',12),
    highlightthickness=0
)
entry_1.place(
    x=30.0,
    y=141.0,
    width=305.0,
    height=45.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=send_email,
    relief="flat"
)
button_1.place(
    x=363.0,
    y=144.0,
    width=41.0,
    height=41.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    108.5,
    304.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font=('Cairo',12),
    highlightthickness=0
)
entry_2.place(
    x=20.0,
    y=277.0,
    width=177.0,
    height=52.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=verify,
    relief="flat"
)
button_2.place(
    x=16.0,
    y=345.0,
    width=129.0,
    height=49.0
)
window.resizable(False, False)
window.mainloop()
